# TEST FILE with missing parameters

# Initial standard deviations
pitch_roll_std: [0.1, 0.1]

# IMU noise statistics
accelerometer_noise_density: 0.01   
accelerometer_random_walk:   0.001
gyroscope_noise_density: 0.01
gyroscope_random_walk:   0.001
